# Mako template file. Note that the variables available here are not the same
# as those available to the main config file.



"""add_procesado_to_mediciones"""

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = "d6aa013a7df1"
down_revision = "001_initial"
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mediciones', sa.Column('procesado', sa.Boolean(), nullable=False))
    op.alter_column('mediciones', 'movimiento',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_mediciones_procesado'), 'mediciones', ['procesado'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mediciones_procesado'), table_name='mediciones')
    op.alter_column('mediciones', 'movimiento',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('mediciones', 'procesado')
    # ### end Alembic commands ###
